title = "AVL Trees"
date = 2004-03-19
topics = [
  "Computer science/Data structures",
]
abstract = "Two formalizations of AVL trees with room for extensions. The first formalization is monolithic and shorter, the second one in two stages, longer and a bit simpler. The final implementation is the same. If you are interested in developing this further, please contact <tt>gerwin.klein@nicta.com.au</tt>."
license = "bsd"
note = ""

[authors]

[authors.nipkow]
homepage = "nipkow_homepage"

[authors.pusch]

[contributors]

[notify]
klein = "klein_email"

[history]
2011-04-11 = "Ondrej Kuncar added delete function"

[extra]

[related]
