title = "BDD Normalisation"
date = 2008-02-29
topics = [
  "Computer science/Data structures",
]
abstract = "We present the verification of the normalisation of a binary decision diagram (BDD). The normalisation follows the original algorithm presented by Bryant in 1986 and transforms an ordered BDD in a reduced, ordered and shared BDD. The verification is based on Hoare logics."
license = "bsd"
note = ""

[authors]

[authors.ortner]

[authors.schirmer]

[contributors]

[notify]
klein = "klein_email"
schirmer = "schirmer_email"

[history]

[extra]
