title = "Category Theory to Yoneda's Lemma"
date = 2005-04-21
topics = [
  "Mathematics/Category theory",
]
abstract = "This development proves Yoneda's lemma and aims to be readable by humans. It only defines what is needed for the lemma: categories, functors and natural transformations. Limits, adjunctions and other important concepts are not included."
license = "lgpl"
note = ""

[authors]

[authors.keefe]
homepage = "keefe_homepage"

[contributors]

[notify]
paulson = "paulson_email"

[history]
2010-04-23 = "The definition of the constant <tt>equinumerous</tt> was slightly too weak in the original submission and has been fixed in revision <a href=\"https://foss.heptapod.net/isa-afp/afp-devel/-/commit/3498bb1e4c7ba468db8588eb7184c1849641f7d3\">8c2b5b3c995f</a>."

[extra]

[related]
