title = "Category Theory with Adjunctions and Limits"
date = 2016-06-26
topics = [
  "Mathematics/Category theory",
]
abstract = """
<p>
This article attempts to develop a usable framework for doing category
theory in Isabelle/HOL.  Our point of view, which to some extent
differs from that of the previous AFP articles on the subject, is to
try to explore how category theory can be done efficaciously within
HOL, rather than trying to match exactly the way things are done using
a traditional approach.  To this end, we define the notion of category
in an \"object-free\" style, in which a category is represented by a
single partial composition operation on arrows.  This way of defining
categories provides some advantages in the context of HOL, including
the ability to avoid the use of records and the possibility of
defining functors and natural transformations simply as certain
functions on arrows, rather than as composite objects.  We define
various constructions associated with the basic notions, including:
dual category, product category, functor category, discrete category,
free category, functor composition, and horizontal and vertical
composite of natural transformations.  A \"set category\" locale is
defined that axiomatizes the notion \"category of all sets at a type
and all functions between them,\" and a fairly extensive set of
properties of set categories is derived from the locale assumptions.
The notion of a set category is used to prove the Yoneda Lemma in a
general setting of a category equipped with a \"hom embedding,\" which
maps arrows of the category to the \"universe\" of the set category.  We
also give a treatment of adjunctions, defining adjunctions via left
and right adjoint functors, natural bijections between hom-sets, and
unit and counit natural transformations, and showing the equivalence
of these definitions.  We also develop the theory of limits, including
representations of functors, diagrams and cones, and diagonal
functors.  We show that right adjoint functors preserve limits, and
that limits can be constructed via products and equalizers.  We
characterize the conditions under which limits exist in a set
category. We also examine the case of limits in a functor category,
ultimately culminating in a proof that the Yoneda embedding preserves
limits.
</p><p>
Revisions made subsequent to the first version of this article added
material on equivalence of categories, cartesian categories,
categories with pullbacks, categories with finite limits, and
cartesian closed categories.  A construction was given of the category
of hereditarily finite sets and functions between them, and it was
shown that this category is cartesian closed.
Using \"ZFC_in_HOL\", a construction was also given of the (large)
category of small sets and functions between them, and it was shown
that this category is small-complete.
</p>"""
license = "bsd"
note = ""

[authors]

[authors.stark]
email = "stark_email"

[contributors]

[notify]
stark = "stark_email"

[history]
2021-07-22 = """
Minor changes to sublocale declarations related to functor/natural transformation to
avoid issues with global interpretations reported 2/2/2021 by Filip Smola.
(revision 49d3aa43c180)<br>"""
2018-05-29 = """
Revised axioms for the category locale.  Introduced notation for composition and \"in hom\".
(revision 8318366d4575)<br>
"""
2020-02-15 = """
Move ConcreteCategory.thy from Bicategory to Category3 and use it systematically.
Make other minor improvements throughout.
(revision a51840d36867)<br>
"""
2020-07-10 = """
Added new material, mostly centered around cartesian categories.
(revision 06640f317a79)<br>
"""
2020-11-04 = """
Minor modifications and extensions made in conjunction with the addition
of new material to Bicategory.
(revision 472cb2268826)<br>
"""

[extra]

[related]
