title = "Completeness theorem"
date = 2004-09-20
topics = [
  "Logic/Proof theory",
]
abstract = "The completeness of first-order logic is proved, following the first five pages of Wainer and Wallen's chapter of the book <i>Proof Theory</i> by Aczel et al., CUP, 1992. Their presentation of formulas allows the proofs to use symmetry arguments. Margetson formalized this theorem by early 2000. The Isar conversion is thanks to Tom Ridge. A paper describing the formalization is available <a href=\"Completeness-paper.pdf\">[pdf]</a>."
license = "bsd"
note = ""

[authors]

[authors.margetson]

[authors.ridge]

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]

[related]
