title = "Decreasing Diagrams II"
date = 2015-08-20
topics = [
  "Logic/Rewriting",
]
abstract = "This theory formalizes the commutation version of decreasing diagrams for Church-Rosser modulo. The proof follows Felgenhauer and van Oostrom (RTA 2013). The theory also provides important specializations, in particular van Oostromâ€™s conversion version (TCS 2008) of decreasing diagrams."
license = "lgpl"
note = ""

[authors]

[authors.felgenhauer]
email = "felgenhauer_email"

[contributors]

[notify]
felgenhauer = "felgenhauer_email"

[history]

[extra]
