title = "Proving the Correctness of Disk Paxos"
date = 2005-06-22
topics = [
  "Computer science/Algorithms/Distributed",
]
abstract = "Disk Paxos is an algorithm for building arbitrary fault-tolerant distributed systems. The specification of Disk Paxos has been proved correct informally and tested using the TLC model checker, but up to now, it has never been fully formally verified. In this work we have formally verified its correctness using the Isabelle theorem prover and the HOL logic system, showing that Isabelle is a practical tool for verifying properties of TLA+ specifications."
license = "bsd"
note = ""

[authors]

[authors.jaskelioff]
homepage = "jaskelioff_homepage"

[authors.merz]
homepage = "merz_homepage"

[contributors]

[notify]
klein = "klein_email"

[history]

[extra]

[related]
