title = "Ergodic Theory"
date = 2015-12-01
topics = [
  "Mathematics/Probability theory",
]
abstract = "Ergodic theory is the branch of mathematics that studies the behaviour of measure preserving transformations, in finite or infinite measure. It interacts both with probability theory (mainly through measure theory) and with geometry as a lot of interesting examples are from geometric origin. We implement the first definitions and theorems of ergodic theory, including notably Poicar√© recurrence theorem for finite measure preserving systems (together with the notion of conservativity in general), induced maps, Kac's theorem, Birkhoff theorem (arguably the most important theorem in ergodic theory), and variations around it such as conservativity of the corresponding skew product, or Atkinson lemma."
license = "bsd"
note = ""

[authors]

[authors.gouezel]
email = "gouezel_email"

[contributors]

[contributors.eberl]
homepage = "eberl_homepage"

[notify]
gouezel = "gouezel_email"
hoelzl = "hoelzl_email"

[history]

[extra]

[related]
