title = "Functional Automata"
date = 2004-03-30
topics = [
  "Computer science/Automata and formal languages",
]
abstract = "This theory defines deterministic and nondeterministic automata in a functional representation: the transition function/relation and the finality predicate are just functions. Hence the state space may be infinite. It is shown how to convert regular expressions into such automata. A scanner (generator) is implemented with the help of functional automata: the scanner chops the input up into longest recognized substrings. Finally we also show how to convert a certain subclass of functional automata (essentially the finite deterministic ones) into regular sets."
license = "bsd"
note = ""

[authors]

[authors.nipkow]
homepage = "nipkow_homepage"

[contributors]

[notify]
nipkow = "nipkow_email"

[history]

[extra]

[related]
