title = "Gauss-Jordan Algorithm and Its Applications"
date = 2014-09-03
topics = [
  "Computer science/Algorithms/Mathematical",
]
abstract = "The Gauss-Jordan algorithm states that any matrix over a field can be transformed by means of elementary row operations to a matrix in reduced row echelon form. The formalization is based on the Rank Nullity Theorem entry of the AFP and on the HOL-Multivariate-Analysis session of Isabelle, where matrices are represented as functions over finite types. We have set up the code generator to make this representation executable. In order to improve the performance, a refinement to immutable arrays has been carried out. We have formalized some of the applications of the Gauss-Jordan algorithm. Thanks to this development, the following facts can be computed over matrices whose elements belong to a field: Ranks, Determinants, Inverses, Bases and dimensions and Solutions of systems of linear equations. Code can be exported to SML and Haskell."
license = "bsd"
note = ""

[authors]

[authors.divason]
homepage = "divason_homepage"

[authors.aransay]
homepage = "aransay_homepage"

[contributors]

[notify]
divason = "divason_email"
aransay = "aransay_email"

[history]

[extra]
