title = "Formalization of a Generalized Protocol for Clock Synchronization"
date = 2005-06-24
topics = [
  "Computer science/Algorithms/Distributed",
]
abstract = "We formalize the generalized Byzantine fault-tolerant clock synchronization protocol of Schneider. This protocol abstracts from particular algorithms or implementations for clock synchronization. This abstraction includes several assumptions on the behaviors of physical clocks and on general properties of concrete algorithms/implementations. Based on these assumptions the correctness of the protocol is proved by Schneider. His proof was later verified by Shankar using the theorem prover EHDM (precursor to PVS). Our formalization in Isabelle/HOL is based on Shankar's formalization."
license = "bsd"
note = ""

[authors]

[authors.tiu]
homepage = "tiu_homepage"

[contributors]

[notify]
klein = "klein_email"

[history]

[extra]
