title = "Imperative Insertion Sort"
date = 2014-09-25
topics = [
  "Computer science/Algorithms",
]
abstract = "The insertion sort algorithm of Cormen et al. (Introduction to Algorithms) is expressed in Imperative HOL and proved to be correct and terminating. For this purpose we also provide a theory about imperative loop constructs with accompanying induction/invariant rules for proving partial and total correctness. Furthermore, the formalized algorithm is fit for code generation."
license = "bsd"
note = ""

[authors]

[authors.sternagel]
email = "sternagel_email"

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]
