title = "Gödel's Incompleteness Theorems"
date = 2013-11-17
topics = [
  "Logic/Proof theory",
]
abstract = """
Gödel's two incompleteness theorems are formalised, following a careful  <a href=\"http://journals.impan.gov.pl/dm/Inf/422-0-1.html\">presentation</a> by Swierczkowski, in the theory of <a href=\"HereditarilyFinite.html\">hereditarily finite sets</a>. This represents the first ever machine-assisted proof of the second incompleteness theorem. Compared with traditional formalisations using Peano arithmetic (see e.g. Boolos), coding is simpler, with no need to formalise the notion
of multiplication (let alone that of a prime number)
in the formalised calculus upon which the theorem is based.
However, other technical problems had to be solved in order to complete the argument."""
license = "bsd"
note = ""

[authors]

[authors.paulson]
homepage = "paulson_homepage"

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]

[related]
