title = "Inductive Study of Confidentiality"
date = 2012-05-02
topics = [
  "Computer science/Security",
]
abstract = "This document contains the full theory files accompanying article <i>Inductive Study of Confidentiality --- for Everyone</i> in <i>Formal Aspects of Computing</i>. They aim at an illustrative and didactic presentation of the Inductive Method of protocol analysis, focusing on the treatment of one of the main goals of security protocols: confidentiality against a threat model. The treatment of confidentiality, which in fact forms a key aspect of all protocol analysis tools, has been found cryptic by many learners of the Inductive Method, hence the motivation for this work. The theory files in this document guide the reader step by step towards design and proof of significant confidentiality theorems. These are developed against two threat models, the standard Dolev-Yao and a more audacious one, the General Attacker, which turns out to be particularly useful also for teaching purposes."
license = "bsd"
note = ""

[authors]

[authors.bella]
homepage = "bella_homepage"

[contributors]

[notify]
bella = "bella_email"

[history]

[extra]

[related]
