title = "Matrices, Jordan Normal Forms, and Spectral Radius Theory"
date = 2015-08-21
topics = [
  "Mathematics/Algebra",
]
abstract = """
<p>
Matrix interpretations are useful as measure functions in termination proving. In order to use these interpretations also for complexity analysis, the growth rate of matrix powers has to examined. Here, we formalized a central result of spectral radius theory, namely that the growth rate is polynomially bounded if and only if the spectral radius of a matrix is at most one.
</p><p>
To formally prove this result we first studied the growth rates of matrices in Jordan normal form, and prove the result that every complex matrix has a Jordan normal form using a constructive prove via Schur decomposition.
</p><p>
The whole development is based on a new abstract type for matrices, which is also executable by a suitable setup of the code generator. It completely subsumes our former AFP-entry on executable matrices, and its main advantage is its close connection to the HMA-representation which allowed us to easily adapt existing proofs on determinants.
</p><p>
All the results have been applied to improve CeTA, our certifier to validate termination and complexity proof certificates.
</p>"""
license = "bsd"
note = ""

[authors]

[authors.thiemann]
email = "thiemann_email"

[authors.yamada]
email = "yamada_email"

[contributors]

[contributors.bentkamp]
email = "bentkamp_email"

[notify]
thiemann = "thiemann_email"
yamada = "yamada_email1"

[history]
2016-01-07 = """
Added Schur-decomposition, Gram-Schmidt orthogonalization, uniqueness of Jordan normal forms<br/>
"""
2018-04-17 = "Integrated lemmas from deep-learning AFP-entry of Alexander Bentkamp"

[extra]

[related]
