title = "The Jordan-Hölder Theorem"
date = 2014-09-09
topics = [
  "Mathematics/Algebra",
]
abstract = "This submission contains theories that lead to a formalization of the proof of the Jordan-Hölder theorem about composition series of finite groups. The theories formalize the notions of isomorphism classes of groups, simple groups, normal series, composition series, maximal normal subgroups. Furthermore, they provide proofs of the second isomorphism theorem for groups, the characterization theorem for maximal normal subgroups as well as many useful lemmas about normal subgroups and factor groups. The proof is inspired by course notes of Stuart Rankin."
license = "bsd"
note = ""

[authors]

[authors.raumer]
email = "raumer_email"

[contributors]

[notify]
raumer = "raumer_email"

[history]

[extra]
