title = "Knowledge-based programs"
date = 2011-05-17
topics = [
  "Computer science/Automata and formal languages",
]
abstract = "Knowledge-based programs (KBPs) are a formalism for directly relating agents' knowledge and behaviour. Here we present a general scheme for compiling KBPs to executable automata with a proof of correctness in Isabelle/HOL. We develop the algorithm top-down, using Isabelle's locale mechanism to structure these proofs, and show that two classic examples can be synthesised using Isabelle's code generator."
license = "bsd"
note = ""

[authors]

[authors.gammie]
homepage = "gammie_homepage"

[contributors]

[notify]
klein = "klein_email"

[history]
2012-03-06 = "Add some more views and revive the code generation."

[extra]
