title = "The Königsberg Bridge Problem and the Friendship Theorem"
date = 2013-07-19
topics = [
  "Mathematics/Graph theory",
]
abstract = "This development provides a formalization of undirected graphs and simple graphs, which are based on Benedikt Nordhoff and Peter Lammich's simple formalization of labelled directed graphs in the archive. Then, with our formalization of graphs, we show both necessary and sufficient conditions for Eulerian trails and circuits as well as the fact that the Königsberg Bridge Problem does not have a solution. In addition, we show the Friendship Theorem in simple graphs."
license = "bsd"
note = ""

[authors]

[authors.li]
homepage = "li_homepage"

[contributors]

[notify]

[history]

[extra]
