title = "Landau Symbols"
date = 2015-07-14
topics = [
  "Mathematics/Analysis",
]
abstract = "This entry provides Landau symbols to describe and reason about the asymptotic growth of functions for sufficiently large inputs. A number of simplification procedures are provided for additional convenience: cancelling of dominated terms in sums under a Landau symbol, cancelling of common factors in products, and a decision procedure for Landau expressions containing products of powers of functions like x, ln(x), ln(ln(x)) etc."
license = "bsd"
note = ""

[authors]

[authors.eberl]
homepage = "eberl_homepage"

[contributors]

[notify]
eberl = "eberl_email"

[history]

[extra]
