title = "Interval Temporal Logic on Natural Numbers"
date = 2011-02-23
topics = [
  "Logic/General logic/Temporal logic",
]
abstract = "We introduce a theory of temporal logic operators using sets of natural numbers as time domain, formalized in a shallow embedding manner. The theory comprises special natural intervals (theory IL_Interval: open and closed intervals, continuous and modulo intervals, interval traversing results), operators for shifting intervals to left/right on the number axis as well as expanding/contracting intervals by constant factors (theory IL_IntervalOperators.thy), and ultimately definitions and results for unary and binary temporal operators on arbitrary natural sets (theory IL_TemporalOperators)."
license = "bsd"
note = ""

[authors]

[authors.trachtenherz]

[contributors]

[notify]
nipkow = "nipkow_email"

[history]

[extra]

[related]
