title = "POPLmark Challenge Via de Bruijn Indices"
date = 2007-08-02
topics = [
  "Computer science/Programming languages/Lambda calculi",
]
abstract = "We present a solution to the POPLmark challenge designed by Aydemir et al., which has as a goal the formalization of the meta-theory of System F<sub>&lt;:</sub>. The formalization is carried out in the theorem prover Isabelle/HOL using an encoding based on de Bruijn indices. We start with a relatively simple formalization covering only the basic features of System F<sub>&lt;:</sub>, and explain how it can be extended to also cover records and more advanced binding constructs."
license = "bsd"
note = ""

[authors]

[authors.berghofer]
homepage = "berghofer_homepage"

[contributors]

[notify]
berghofer = "berghofer_email"

[history]

[extra]

[related]
