title = "Pratt's Primality Certificates"
date = 2013-07-22
topics = [
  "Mathematics/Number theory",
]
abstract = "In 1975, Pratt introduced a proof system for certifying primes. He showed that a number <i>p</i> is prime iff a primality certificate for <i>p</i> exists. By showing a logarithmic upper bound on the length of the certificates in size of the prime number, he concluded that the decision problem for prime numbers is in NP. This work formalizes soundness and completeness of Pratt's proof system as well as an upper bound for the size of the certificate."
license = "bsd"
note = ""

[authors]

[authors.wimmer]
email = "wimmer_email"

[authors.noschinski]
homepage = "noschinski_homepage"

[contributors]

[notify]
noschinski = "noschinski_email"
wimmer = "wimmer_email"

[history]

[extra]
