title = "Probabilistic Noninterference"
date = 2014-03-11
topics = [
  "Computer science/Security",
]
abstract = "We formalize a probabilistic noninterference for a multi-threaded language with uniform scheduling, where probabilistic behaviour comes from both the scheduler and the individual threads. We define notions probabilistic noninterference in two variants: resumption-based and trace-based. For the resumption-based notions, we prove compositionality w.r.t. the language constructs and establish sound type-system-like syntactic criteria. This is a formalization of the mathematical development presented at CPP 2013 and CALCO 2013. It is the probabilistic variant of the Possibilistic Noninterference AFP entry."
license = "bsd"
note = ""

[authors]

[authors.popescu]
homepage = "popescu_homepage"

[authors.hoelzl]
homepage = "hoelzl_homepage"

[contributors]

[notify]
hoelzl = "hoelzl_email"

[history]

[extra]

[related]
