title = "Ramsey's theorem, infinitary version"
date = 2004-09-20
topics = [
  "Mathematics/Combinatorics",
]
abstract = "This formalization of Ramsey's theorem (infinitary version) is taken from Boolos and Jeffrey, <i>Computability and Logic</i>, 3rd edition, Chapter 26. It differs slightly from the text by assuming a slightly stronger hypothesis. In particular, the induction hypothesis is stronger, holding for any infinite subset of the naturals. This avoids the rather peculiar mapping argument between kj and aikj on p.263, which is unnecessary and slightly mars this really beautiful result."
license = "bsd"
note = ""

[authors]

[authors.ridge]

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]

[related]
