title = "Properties of Random Graphs -- Subgraph Containment"
date = 2014-02-13
topics = [
  "Mathematics/Graph theory",
  "Mathematics/Probability theory",
]
abstract = "Random graphs are graphs with a fixed number of vertices, where each edge is present with a fixed probability. We are interested in the probability that a random graph contains a certain pattern, for example a cycle or a clique. A very high edge probability gives rise to perhaps too many edges (which degrades performance for many algorithms), whereas a low edge probability might result in a disconnected graph. We prove a theorem about a threshold probability such that a higher edge probability will asymptotically almost surely produce a random graph with the desired subgraph."
license = "bsd"
note = ""

[authors]

[authors.hupel]
email = "hupel_email"

[contributors]

[notify]
hupel = "hupel_email"

[history]

[extra]
