title = "Recursion Theory I"
date = 2008-04-05
topics = [
  "Logic/Computability",
]
abstract = "This document presents the formalization of introductory material from  recursion theory --- definitions and basic properties of primitive recursive  functions, Cantor pairing function and computably enumerable sets  (including a proof of existence of a one-complete computably enumerable set  and a proof of the Rice's theorem)."
license = "bsd"
note = ""

[authors]

[authors.nedzelsky]

[contributors]

[notify]
nedzelsky = "nedzelsky_email"

[history]

[extra]
