title = "Ribbon Proofs"
date = 2013-01-19
topics = [
  "Computer science/Programming languages/Logics",
]
abstract = "This document concerns the theory of ribbon proofs: a diagrammatic proof system, based on separation logic, for verifying program correctness. We include the syntax, proof rules, and soundness results for two alternative formalisations of ribbon proofs. <p> Compared to traditional proof outlines, ribbon proofs emphasise the structure of a proof, so are intelligible and pedagogical. Because they contain less redundancy than proof outlines, and allow each proof step to be checked locally, they may be more scalable. Where proof outlines are cumbersome to modify, ribbon proofs can be visually manoeuvred to yield proofs of variant programs."
license = "bsd"
note = ""

[authors]

[authors.wickerson]

[contributors]

[notify]

[history]

[extra]

[related]
