title = "Some classical results in Social Choice Theory"
date = 2008-11-09
topics = [
  "Mathematics/Games and economics",
]
abstract = "Drawing on Sen's landmark work \"Collective Choice and Social Welfare\" (1970), this development proves Arrow's General Possibility Theorem, Sen's Liberal Paradox and May's Theorem in a general setting. The goal was to make precise the classical statements and proofs of these results, and to provide a foundation for more recent results such as the Gibbard-Satterthwaite and Duggan-Schwartz theorems."
license = "bsd"
note = ""

[authors]

[authors.gammie]
homepage = "gammie_homepage"

[contributors]

[notify]
nipkow = "nipkow_email"

[history]

[extra]

[related]
