title = "Separation Algebra"
date = 2012-05-11
topics = [
  "Computer science/Programming languages/Logics",
]
abstract = "We present a generic type class implementation of separation algebra for Isabelle/HOL as well as lemmas and generic tactics which can be used directly for any instantiation of the type class. <P> The ex directory contains example instantiations that include structures such as a heap or virtual memory. <P> The abstract separation algebra is based upon \"Abstract Separation Logic\" by Calcagno et al. These theories are also the basis of the ITP 2012 rough diamond \"Mechanised Separation Algebra\" by the authors. <P> The aim of this work is to support and significantly reduce the effort for future separation logic developments in Isabelle/HOL by factoring out the part of separation logic that can be treated abstractly once and for all. This includes developing typical default rule sets for reasoning as well as automated tactic support for separation logic."
license = "bsd"
note = ""

[authors]

[authors.klein]
email = "klein_email"

[authors.kolanski]
email = "kolanski_email"

[authors.boyton]
email = "boyton_email"

[contributors]

[notify]
klein = "klein_email"
kolanski = "kolanski_email"

[history]

[extra]
