title = "An Axiomatic Characterization of the Single-Source Shortest Path Problem"
date = 2013-05-22
topics = [
  "Mathematics/Graph theory",
]
abstract = "This theory is split into two sections. In the first section, we give a formal proof that a well-known axiomatic characterization of the single-source shortest path problem is correct. Namely, we prove that in a directed graph with a non-negative cost function on the edges the single-source shortest path function is the only function that satisfies a set of four axioms. In the second section, we give a formal proof of the correctness of an axiomatic characterization of the single-source shortest path problem for directed graphs with general cost functions. The axioms here are more involved because we have to account for potential negative cycles in the graph. The axioms are summarized in three Isabelle locales."
license = "bsd"
note = ""

[authors]

[authors.rizkallah]
homepage = "rizkallah_homepage"

[contributors]

[notify]

[history]

[extra]

[related]
