title = "Real-Valued Special Functions: Upper and Lower Bounds"
date = 2014-08-29
topics = [
  "Mathematics/Analysis",
]
abstract = "This development proves upper and lower bounds for several familiar real-valued functions. For sin, cos, exp and sqrt, it defines and verifies infinite families of upper and lower bounds, mostly based on Taylor series expansions. For arctan, ln and exp, it verifies a finite collection of upper and lower bounds, originally obtained from the functions' continued fraction expansions using the computer algebra system Maple. A common theme in these proofs is to take the difference between a function and its approximation, which should be zero at one point, and then consider the sign of the derivative. The immediate purpose of this development is to verify axioms used by MetiTarski, an automatic theorem prover for real-valued special functions. Crucial to MetiTarski's operation is the provision of upper and lower bounds for each function of interest."
license = "bsd"
note = ""

[authors]

[authors.paulson]
homepage = "paulson_homepage"

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]
