title = "Stellar Quorum Systems"
date = 2019-08-01
topics = [
  "Computer science/Algorithms/Distributed",
]
abstract = """
We formalize the static properties of personal Byzantine quorum
systems (PBQSs) and Stellar quorum systems, as described in the paper
“Stellar Consensus by Instantiation”, DISC 2019."""
license = "bsd"
note = ""

[authors]

[authors.losa]
email = "losa_email"

[contributors]

[notify]
losa = "losa_email"

[history]

[extra]

[related]
