title = "Topology"
date = 2004-04-26
topics = [
  "Mathematics/Topology",
]
abstract = "This entry contains two theories. The first, <code>Topology</code>, develops the basic notions of general topology. The second, which can be viewed as a demonstration of the first, is called <code>LList_Topology</code>. It develops the topology of lazy lists."
license = "bsd"
note = ""

[authors]

[authors.friedrich]

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]

[related]
