title = "Tree Automata"
date = 2009-11-25
topics = [
  "Computer science/Automata and formal languages",
]
abstract = "This work presents a machine-checked tree automata library for Standard-ML, OCaml and Haskell. The algorithms are efficient by using appropriate data structures like RB-trees. The available algorithms for non-deterministic automata include membership query, reduction, intersection, union, and emptiness check with computation of a witness for non-emptiness. The executable algorithms are derived from less-concrete, non-executable algorithms using data-refinement techniques. The concrete data structures are from the Isabelle Collections Framework. Moreover, this work contains a formalization of the class of tree-regular languages and its closure properties under set operations."
license = "bsd"
note = ""

[authors]

[authors.lammich]
homepage = "lammich_homepage"

[contributors]

[notify]
lammich = "lammich_email1"
nipkow = "nipkow_email"

[history]

[extra]
