title = "Two Theorems on Hermitian Matrices"
date = 2024-11-16
topics = [
  "Mathematics/Algebra",
]
abstract = """
We formalize two results on Hermitian matrices. First, Sylvester's criterion: a Hermitian matrix is positive definite if and only if all its leading principal submatrices have positive determinant. Second, Cauchy's eigenvalue interlacing theorem: given a principal submatrix \\(B\\) of a Hermitian matrix \\(A\\), the eigenvalues of \\(B\\) interlace those of \\(A\\).

Our approach to Sylvester's criterion is fairly standard, and required us to formalize Schur's block matrix determinant formula, which gives a formula for the determinant of a block matrix \\((A, B, C, D)\\) when \\(A\\) is invertible.

Our approach to Cauchy's eigenvalue interlacing theorem follows a proof given in a set of lecture notes by Dr. David Bindel. This approach involved formalizing the Courant-Fischer minimax theorem (a theorem about the Rayleigh quotient, which we define in this entry). In our statement of the Courant-Fischer minimax theorem, we refer to the infimum and supremum instead of the minimum and maximum, as this simplifies the proof and is sufficient to prove Cauchy's eigenvalue interlacing theorem."""
license = "bsd"
note = ""

[authors]

[authors.binder]
email = "binder_email"

[authors.jiangz]
homepage = "jiangz_homepage"

[contributors]

[notify]
binder = "binder_email"

[history]
2025-11-23 = """
In Cauchy_Eigenvalue_Interlacing.thy, improved some proofs and definitions, and extracted some specialized subproofs to more general reusable lemmas (placed in Misc_Matrix_Results.thy). Also, in Sylvester_Criterion.thy, added computable definition to check if the smallest eigenvalue of a matrix is less than a given value (along with proof of correctness).
(revision 981ea49ca51a)<br>
"""

[extra]

[related]
dois = []
pubs = []
