title = "Universal Hash Families"
date = 2022-02-20
topics = [
  "Computer science/Algorithms/Randomized",
]
abstract = """
A <i>k</i>-universal hash family is a probability
space of functions, which have uniform distribution and form
<i>k</i>-wise independent random variables. They can often be used
in place of classic (or cryptographic) hash functions and allow the
rigorous analysis of the performance of randomized algorithms and
data structures that rely on hash functions. In 1981
<a href=\"https://doi.org/10.1016/0022-0000(81)90033-7\">Wegman and Carter</a>
introduced a generic construction for such families with arbitrary
<i>k</i> using polynomials over a finite field. This entry
contains a formalization of them and establishes the property of
<i>k</i>-universality. To be useful the formalization also provides
an explicit construction of finite fields using the factor ring of
integers modulo a prime. Additionally, some generic results about
independent families are shown that might be of independent interest."""
license = "bsd"
note = ""

[authors]

[authors.karayel]
homepage = "karayel_homepage"

[contributors]

[notify]
karayel = "karayel_email"

[history]
2024-01-25 = "Added combinator library for pseudorandom objects."

[extra]

[related]
