title = "Fundamental Properties of Valuation Theory and Hensel's Lemma"
date = 2007-08-08
topics = [
  "Mathematics/Algebra",
]
abstract = "Convergence with respect to a valuation is discussed as convergence of a Cauchy sequence. Cauchy sequences of polynomials are defined. They are used to formalize Hensel's lemma."
license = "bsd"
note = ""

[authors]

[authors.kobayashi]

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]
