title = "A Mechanically Verified, Efficient, Sound and Complete Theorem Prover For First Order Logic"
date = 2004-09-28
topics = [
  "Logic/General logic/Mechanization of proofs",
]
abstract = "Soundness and completeness for a system of first order logic are formally proved, building on James Margetson's formalization of work by Wainer and Wallen. The completeness proofs naturally suggest an algorithm to derive proofs. This algorithm, which can be implemented tail recursively, is formalized in Isabelle/HOL. The algorithm can be executed via the rewriting tactics of Isabelle. Alternatively, the definitions can be exported to OCaml, yielding a directly executable program."
license = "bsd"
note = ""

[authors]

[authors.ridge]

[contributors]

[notify]
paulson = "paulson_email"

[history]

[extra]

[related]
