title = "Finite Machine Word Library"
date = 2016-06-09
topics = [
  "Computer science/Data structures",
]
abstract = """
This entry contains an extension to the Isabelle library for
fixed-width machine words. In particular, the entry adds quickcheck setup
for words, printing as hexadecimals, additional operations, reasoning
about alignment, signed words, enumerations of words, normalisation of
word numerals, and an extensive library of properties about generic
fixed-width words, as well as an instantiation of many of these to the
commonly used 32 and 64-bit bases."""
license = "bsd"
note = ""

[authors]

[authors.beeren]

[authors.fernandez]

[authors.gao]

[authors.klein]
homepage = "klein_homepage"

[authors.kolanski]

[authors.lim]

[authors.lewis]

[authors.matichuk]

[authors.sewell]

[contributors]

[notify]
klein = "klein_email1"

[history]

[extra]
